name: Build Docker Image

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  packages: write

jobs:

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run:
          rustup update stable && rustup default stable

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release && cp target/release/server rsauth-server # we move the build artifact so we can dockerignore "target/"

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and Push Docker
        run: |-
          docker build --push \
            -t ghcr.io/${{ github.repository }}:latest \
            -t ghcr.io/${{ github.repository }}:$GITHUB_SHA \
            .
