name: Build Docker Image

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  packages: write

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Set up aarch64 GCC
        run:
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Set up Rust
        run:
          rustup update stable && rustup default stable && rustup target add aarch64-unknown-linux-gnu

      - uses: Swatinem/rust-cache@v2

      - name: Build AMD64
        run: cargo build --release && cp target/release/server rsauth-server-amd64 # we move the build artifact so we can dockerignore "target/"

      - name: Build ARM64
        run: cargo build --release --target aarch64-unknown-linux-gnu && cp target/aarch64-unknown-linux-gnu/release/server rsauth-server-arm64 # we move the build artifact so we can dockerignore "target/"

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and Push Docker
        run: |-
          docker build --push --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ github.repository }}:latest \
            -t ghcr.io/${{ github.repository }}:$GITHUB_SHA \
            .
